// GENERATED FILE - do not edit by hand.
// Regenerated by quickshell/tools/palette.py from the wallpaper.
//
// Material 3 roles derived from: whv.jpg
// Seed colour: #3e5594 (ranked)
pragma Singleton
import QtQuick

QtObject {
    readonly property string mode: "dark"

    readonly property color bg: "#1b1b1f"
    readonly property color surface: "#1b1b1f"
    readonly property color surface2: "#1f1f23"
    readonly property color surface3: "#292a2d"
    readonly property color border: "#45464f"
    readonly property color text: "#e4e2e6"
    readonly property color muted: "#c5c6d0"
    readonly property color muted2: "#8f909a"
    readonly property color accent: "#b3c5ff"
    readonly property color accent2: "#3d5ba9"
    readonly property color accentStrong: "#214290"
    readonly property color secondary: "#c1c6dd"
    readonly property color secondary2: "#e1bbdc"
    readonly property color secondaryStrong: "#414659"
    readonly property color critical: "#ffb4ab"
    readonly property color onAccentText: "#002a76"
    readonly property string panelOverlay: "rgba(0, 0, 0, 0.74)"
}
