"""Regression tests for the Material 3 color engine.

Golden palette values were generated by running the upstream Java reference
implementation (material-color-utilities, Apache-2.0) as an oracle. The
TonalPalette / CorePalette values below must match it exactly.

Note on scheme roles: this module implements the classic Material 3 baseline
role set (the tones documented in the 2021 M3 baseline). The current upstream
library additionally applies contrast curves and newer tone assignments in
SchemeTonalSpot / ColorSpec2025. That is policy layered on top of the same
color science, which is what the golden values below pin down.

Usage:  python3 tools/verify_m3.py
"""

import sys

try:
    from m3color import (
        Hct,
        TonalPalette,
        CorePalette,
        hex_from_argb,
        argb_from_hex,
    )
except ImportError:
    sys.exit("run from quickshell/tools/ or with tools/ on PYTHONPATH")

# TonalPalette tones, generated by the upstream Java reference at these
# (hue, chroma) pairs. Any deviation means the CAM16/HCT math regressed.
GOLDEN_PALETTES = {
    "a1": (298.980997210704, 48.0, [
        "#000000", "#13003a", "#190048", "#22005d", "#260561", "#31166c", "#381e72", "#3c2377", "#41287c", "#4f378a", "#6750a4", "#8069bf", "#9a83db", "#cfbcff", "#e1d3ff", "#e9ddff", "#eee4ff", "#f3eaff", "#f6eeff", "#f8f1ff", "#fdf7ff",
    ]),
    "a2": (298.980997210704, 16.0, [
        "#000000", "#100b1d", "#151022", "#1e192b", "#221d2f", "#2c273a", "#332d41", "#373245", "#3c364a", "#4a4458", "#625b71", "#7b748a", "#958da4", "#cbc2db", "#dfd6ef", "#e8def8", "#eee4fe", "#f3eaff", "#f6eeff", "#f8f1ff", "#fdf7ff",
    ]),
    "n2": (298.980997210704, 8.0, [
        "#000000", "#0f0d14", "#14121a", "#1d1a22", "#211e26", "#2b2931", "#322f38", "#36333c", "#3b3840", "#49454e", "#615d66", "#7a757f", "#948f99", "#cac4cf", "#ded8e3", "#e7e0eb", "#ece6f1", "#f2ebf7", "#f5eefa", "#f8f1fd", "#fdf7ff",
    ]),
    "error": (25.0, 84.0, [
        "#000000", "#280001", "#310001", "#410002", "#490002", "#5c0004", "#690005", "#710005", "#790006", "#93000a", "#ba1a1a", "#de3730", "#ff5449", "#ffb4ab", "#ffcfc9", "#ffdad6", "#ffe2de", "#ffe9e6", "#ffedea", "#fff0ee", "#fff8f7",
    ]),
}


TONES = [0, 4, 6, 10, 12, 17, 20, 22, 24, 30, 40, 50, 60, 80, 87, 90, 92, 94, 95, 96, 98]

# Clipping cases: chroma beyond the sRGB gamut at the given lightness.
GOLDEN_CLIPPING = [
    (0.00, 10.00, 10.00, "#25181c"),
    (0.00, 10.00, 40.00, "#6c5a5e"),
    (0.00, 10.00, 50.00, "#867277"),
    (0.00, 10.00, 90.00, "#f6dce2"),
    (0.00, 10.00, 99.00, "#fffbff"),
    (0.00, 30.00, 10.00, "#360c1d"),
    (0.00, 30.00, 40.00, "#854e60"),
    (0.00, 30.00, 50.00, "#a16678"),
    (0.00, 30.00, 90.00, "#ffd9e2"),
    (0.00, 30.00, 99.00, "#fffbff"),
    (0.00, 48.00, 10.00, "#3e001d"),
    (0.00, 48.00, 40.00, "#984061"),
    (0.00, 48.00, 50.00, "#b6587a"),
    (0.00, 48.00, 90.00, "#ffd9e2"),
    (0.00, 48.00, 99.00, "#fffbff"),
    (0.00, 84.00, 10.00, "#3e001d"),
    (0.00, 84.00, 40.00, "#b90063"),
    (0.00, 84.00, 50.00, "#dc2c7c"),
    (0.00, 84.00, 90.00, "#ffd9e2"),
    (0.00, 84.00, 99.00, "#fffbff"),
    (0.00, 120.00, 10.00, "#3e001d"),
    (0.00, 120.00, 40.00, "#b90063"),
    (0.00, 120.00, 50.00, "#e7007d"),
    (0.00, 120.00, 90.00, "#ffd9e2"),
    (0.00, 120.00, 99.00, "#fffbff"),
    (0.00, 200.00, 10.00, "#3e001d"),
    (0.00, 200.00, 40.00, "#b90063"),
    (0.00, 200.00, 50.00, "#e7007d"),
    (0.00, 200.00, 90.00, "#ffd9e2"),
    (0.00, 200.00, 99.00, "#fffbff"),
    (25.00, 10.00, 10.00, "#271816"),
    (25.00, 10.00, 40.00, "#6e5957"),
    (25.00, 10.00, 50.00, "#88726f"),
    (25.00, 10.00, 90.00, "#f9dcd8"),
    (25.00, 10.00, 99.00, "#fffbff"),
    (25.00, 30.00, 10.00, "#370d0a"),
    (25.00, 30.00, 40.00, "#894e48"),
    (25.00, 30.00, 50.00, "#a6665f"),
    (25.00, 30.00, 90.00, "#ffdad6"),
    (25.00, 30.00, 99.00, "#fffbff"),
    (25.00, 48.00, 10.00, "#410002"),
    (25.00, 48.00, 40.00, "#9c4239"),
    (25.00, 48.00, 50.00, "#bc5950"),
    (25.00, 48.00, 90.00, "#ffdad6"),
    (25.00, 48.00, 99.00, "#fffbff"),
    (25.00, 84.00, 10.00, "#410002"),
    (25.00, 84.00, 40.00, "#ba1a1a"),
    (25.00, 84.00, 50.00, "#de3730"),
    (25.00, 84.00, 90.00, "#ffdad6"),
    (25.00, 84.00, 99.00, "#fffbff"),
    (25.00, 120.00, 10.00, "#410002"),
    (25.00, 120.00, 40.00, "#c00011"),
    (25.00, 120.00, 50.00, "#ef0018"),
    (25.00, 120.00, 90.00, "#ffdad6"),
    (25.00, 120.00, 99.00, "#fffbff"),
    (25.00, 200.00, 10.00, "#410002"),
    (25.00, 200.00, 40.00, "#c00011"),
    (25.00, 200.00, 50.00, "#ef0018"),
    (25.00, 200.00, 90.00, "#ffdad6"),
    (25.00, 200.00, 99.00, "#fffbff"),
    (60.00, 10.00, 10.00, "#25190f"),
    (60.00, 10.00, 40.00, "#6c5b4e"),
    (60.00, 10.00, 50.00, "#867465"),
    (60.00, 10.00, 90.00, "#f6decd"),
    (60.00, 10.00, 99.00, "#fffbff"),
    (60.00, 30.00, 10.00, "#2e1500"),
    (60.00, 30.00, 40.00, "#825429"),
    (60.00, 30.00, 50.00, "#9e6c3f"),
    (60.00, 30.00, 90.00, "#ffdcc1"),
    (60.00, 30.00, 99.00, "#fffbff"),
    (60.00, 48.00, 10.00, "#2e1500"),
    (60.00, 48.00, 40.00, "#8f4e00"),
    (60.00, 48.00, 50.00, "#b06411"),
    (60.00, 48.00, 90.00, "#ffdcc1"),
    (60.00, 48.00, 99.00, "#fffbff"),
    (60.00, 84.00, 10.00, "#2e1500"),
    (60.00, 84.00, 40.00, "#8f4e00"),
    (60.00, 84.00, 50.00, "#b26300"),
    (60.00, 84.00, 90.00, "#ffdcc1"),
    (60.00, 84.00, 99.00, "#fffbff"),
    (60.00, 120.00, 10.00, "#2e1500"),
    (60.00, 120.00, 40.00, "#8f4e00"),
    (60.00, 120.00, 50.00, "#b26300"),
    (60.00, 120.00, 90.00, "#ffdcc1"),
    (60.00, 120.00, 99.00, "#fffbff"),
    (60.00, 200.00, 10.00, "#2e1500"),
    (60.00, 200.00, 40.00, "#8f4e00"),
    (60.00, 200.00, 50.00, "#b26300"),
    (60.00, 200.00, 90.00, "#ffdcc1"),
    (60.00, 200.00, 99.00, "#fffbff"),
    (120.00, 10.00, 10.00, "#1b1d10"),
    (120.00, 10.00, 40.00, "#5e604f"),
    (120.00, 10.00, 50.00, "#777867"),
    (120.00, 10.00, 90.00, "#e3e4cf"),
    (120.00, 10.00, 99.00, "#fdfee8"),
    (120.00, 30.00, 10.00, "#181e00"),
    (120.00, 30.00, 40.00, "#5a632c"),
    (120.00, 30.00, 50.00, "#727c43"),
    (120.00, 30.00, 90.00, "#dee9a4"),
    (120.00, 30.00, 99.00, "#fcffdd"),
    (120.00, 48.00, 10.00, "#181e00"),
    (120.00, 48.00, 40.00, "#566500"),
    (120.00, 48.00, 50.00, "#6e7e18"),
    (120.00, 48.00, 90.00, "#d9ec7b"),
    (120.00, 48.00, 99.00, "#fcffdd"),
    (120.00, 84.00, 10.00, "#181e00"),
    (120.00, 84.00, 40.00, "#566500"),
    (120.00, 84.00, 50.00, "#6d7f00"),
    (120.00, 84.00, 90.00, "#d1f100"),
    (120.00, 84.00, 99.00, "#fcffdd"),
    (120.00, 120.00, 10.00, "#181e00"),
    (120.00, 120.00, 40.00, "#566500"),
    (120.00, 120.00, 50.00, "#6d7f00"),
    (120.00, 120.00, 90.00, "#d1f100"),
    (120.00, 120.00, 99.00, "#fcffdd"),
    (120.00, 200.00, 10.00, "#181e00"),
    (120.00, 200.00, 40.00, "#566500"),
    (120.00, 200.00, 50.00, "#6d7f00"),
    (120.00, 200.00, 90.00, "#d1f100"),
    (120.00, 200.00, 99.00, "#fcffdd"),
    (180.00, 10.00, 10.00, "#121e1b"),
    (180.00, 10.00, 40.00, "#54615d"),
    (180.00, 10.00, 50.00, "#6c7a75"),
    (180.00, 10.00, 90.00, "#d7e6e0"),
    (180.00, 10.00, 99.00, "#f3fffa"),
    (180.00, 30.00, 10.00, "#00201a"),
    (180.00, 30.00, 40.00, "#29695c"),
    (180.00, 30.00, 50.00, "#448274"),
    (180.00, 30.00, 90.00, "#afefde"),
    (180.00, 30.00, 99.00, "#f3fffa"),
    (180.00, 48.00, 10.00, "#00201a"),
    (180.00, 48.00, 40.00, "#006b5b"),
    (180.00, 48.00, 50.00, "#008673"),
    (180.00, 48.00, 90.00, "#78f8dd"),
    (180.00, 48.00, 99.00, "#f3fffa"),
    (180.00, 84.00, 10.00, "#00201a"),
    (180.00, 84.00, 40.00, "#006b5b"),
    (180.00, 84.00, 50.00, "#008673"),
    (180.00, 84.00, 90.00, "#00fedb"),
    (180.00, 84.00, 99.00, "#f3fffa"),
    (180.00, 120.00, 10.00, "#00201a"),
    (180.00, 120.00, 40.00, "#006b5b"),
    (180.00, 120.00, 50.00, "#008673"),
    (180.00, 120.00, 90.00, "#00fedb"),
    (180.00, 120.00, 99.00, "#f3fffa"),
    (180.00, 200.00, 10.00, "#00201a"),
    (180.00, 200.00, 40.00, "#006b5b"),
    (180.00, 200.00, 50.00, "#008673"),
    (180.00, 200.00, 90.00, "#00fedb"),
    (180.00, 200.00, 99.00, "#f3fffa"),
    (240.00, 10.00, 10.00, "#141d23"),
    (240.00, 10.00, 40.00, "#575f67"),
    (240.00, 10.00, 50.00, "#6f7880"),
    (240.00, 10.00, 90.00, "#dbe4ed"),
    (240.00, 10.00, 99.00, "#fbfcff"),
    (240.00, 30.00, 10.00, "#001e2e"),
    (240.00, 30.00, 40.00, "#366380"),
    (240.00, 30.00, 50.00, "#507c9a"),
    (240.00, 30.00, 90.00, "#c8e6ff"),
    (240.00, 30.00, 99.00, "#fbfcff"),
    (240.00, 48.00, 10.00, "#001e2e"),
    (240.00, 48.00, 40.00, "#006590"),
    (240.00, 48.00, 50.00, "#007fb4"),
    (240.00, 48.00, 90.00, "#c8e6ff"),
    (240.00, 48.00, 99.00, "#fbfcff"),
    (240.00, 84.00, 10.00, "#001e2e"),
    (240.00, 84.00, 40.00, "#006590"),
    (240.00, 84.00, 50.00, "#007fb4"),
    (240.00, 84.00, 90.00, "#c8e6ff"),
    (240.00, 84.00, 99.00, "#fbfcff"),
    (240.00, 120.00, 10.00, "#001e2e"),
    (240.00, 120.00, 40.00, "#006590"),
    (240.00, 120.00, 50.00, "#007fb4"),
    (240.00, 120.00, 90.00, "#c8e6ff"),
    (240.00, 120.00, 99.00, "#fbfcff"),
    (240.00, 200.00, 10.00, "#001e2e"),
    (240.00, 200.00, 40.00, "#006590"),
    (240.00, 200.00, 50.00, "#007fb4"),
    (240.00, 200.00, 90.00, "#c8e6ff"),
    (240.00, 200.00, 99.00, "#fbfcff"),
    (299.00, 10.00, 10.00, "#1d1a24"),
    (299.00, 10.00, 40.00, "#615c69"),
    (299.00, 10.00, 50.00, "#7a7582"),
    (299.00, 10.00, 90.00, "#e7e0ef"),
    (299.00, 10.00, 99.00, "#fffbff"),
    (299.00, 30.00, 10.00, "#1f143e"),
    (299.00, 30.00, 40.00, "#645785"),
    (299.00, 30.00, 50.00, "#7d709f"),
    (299.00, 30.00, 90.00, "#e9ddff"),
    (299.00, 30.00, 99.00, "#fffbff"),
    (299.00, 48.00, 10.00, "#22005d"),
    (299.00, 48.00, 40.00, "#6750a4"),
    (299.00, 48.00, 50.00, "#8069bf"),
    (299.00, 48.00, 90.00, "#e9ddff"),
    (299.00, 48.00, 99.00, "#fffbff"),
    (299.00, 84.00, 10.00, "#22005d"),
    (299.00, 84.00, 40.00, "#6e25f5"),
    (299.00, 84.00, 50.00, "#8653ff"),
    (299.00, 84.00, 90.00, "#e9ddff"),
    (299.00, 84.00, 99.00, "#fffbff"),
    (299.00, 120.00, 10.00, "#22005d"),
    (299.00, 120.00, 40.00, "#6f19ff"),
    (299.00, 120.00, 50.00, "#8653ff"),
    (299.00, 120.00, 90.00, "#e9ddff"),
    (299.00, 120.00, 99.00, "#fffbff"),
    (299.00, 200.00, 10.00, "#22005d"),
    (299.00, 200.00, 40.00, "#6f19ff"),
    (299.00, 200.00, 50.00, "#8653ff"),
    (299.00, 200.00, 90.00, "#e9ddff"),
    (299.00, 200.00, 99.00, "#fffbff"),
    (330.00, 10.00, 10.00, "#221921"),
    (330.00, 10.00, 40.00, "#675b65"),
    (330.00, 10.00, 50.00, "#81737e"),
    (330.00, 10.00, 90.00, "#efdeea"),
    (330.00, 10.00, 99.00, "#fffbff"),
    (330.00, 30.00, 10.00, "#2e0e31"),
    (330.00, 30.00, 40.00, "#785177"),
    (330.00, 30.00, 50.00, "#926a91"),
    (330.00, 30.00, 90.00, "#ffd6fb"),
    (330.00, 30.00, 99.00, "#fffbff"),
    (330.00, 48.00, 10.00, "#36003d"),
    (330.00, 48.00, 40.00, "#87458a"),
    (330.00, 48.00, 50.00, "#a25ea5"),
    (330.00, 48.00, 90.00, "#ffd6fb"),
    (330.00, 48.00, 99.00, "#fffbff"),
    (330.00, 84.00, 10.00, "#36003d"),
    (330.00, 84.00, 40.00, "#a400b5"),
    (330.00, 84.00, 50.00, "#c232d1"),
    (330.00, 84.00, 90.00, "#ffd6fb"),
    (330.00, 84.00, 99.00, "#fffbff"),
    (330.00, 120.00, 10.00, "#36003d"),
    (330.00, 120.00, 40.00, "#a400b5"),
    (330.00, 120.00, 50.00, "#cd00e2"),
    (330.00, 120.00, 90.00, "#ffd6fb"),
    (330.00, 120.00, 99.00, "#fffbff"),
    (330.00, 200.00, 10.00, "#36003d"),
    (330.00, 200.00, 40.00, "#a400b5"),
    (330.00, 200.00, 50.00, "#cd00e2"),
    (330.00, 200.00, 90.00, "#ffd6fb"),
    (330.00, 200.00, 99.00, "#fffbff"),
]


def main():
    failures = []

    for label, (hue, chroma, expected) in GOLDEN_PALETTES.items():
        pal = TonalPalette(hue, chroma)
        for i, tone in enumerate(TONES):
            got = pal.tone(tone)
            want = expected[i]
            if got != want:
                failures.append("%s tone(%d) got %s want %s" % (label, tone, got, want))

    for hue, chroma, tone, want in GOLDEN_CLIPPING:
        got = hex_from_argb(Hct.of(hue, chroma, tone).to_int())
        if got != want:
            failures.append("clip(%.0f,%.0f,%.0f) got %s want %s" % (hue, chroma, tone, got, want))

    # Structural invariants.
    neutral = TonalPalette(0.0, 0.0)
    invariants = [
        ("neutral tone 0 == black", neutral.tone(0) == "#000000"),
        ("neutral tone 100 == white", neutral.tone(100) == "#ffffff"),
        ("neutral tone 50 == #777777", neutral.tone(50) == "#777777"),
        ("neutral tone 10 == #1b1b1b", neutral.tone(10) == "#1b1b1b"),
        ("neutral tone 90 == #e2e2e2", neutral.tone(90) == "#e2e2e2"),
        ("hex round-trip", hex_from_argb(argb_from_hex("#a7cdd9")) == "#a7cdd9"),
    ]
    for label, ok in invariants:
        if not ok:
            failures.append("invariant failed: " + label)

    # HCT round-trip stability across the gamut.
    worst_drift = 0.0
    for argb in (
        0xFF000000, 0xFFFFFFFF, 0xFFFF0000, 0xFF00FF00, 0xFF0000FF,
        0xFF6750A4, 0xA7CDD9E9 & 0xFFFFFFFF, 0xFF434766, 0xFFFFD29D,
        0xFF123456, 0xFFFEDCBA, 0xFF0F0F0F, 0xFF2196F3, 0xFFFF00FF, 0xFF00FFFF,
    ):
        original = Hct.from_int(argb)
        roundtripped = Hct.from_int(original.to_int())
        d_hue = min(abs(original.hue - roundtripped.hue), 360.0 - abs(original.hue - roundtripped.hue))
        d_chroma = abs(original.chroma - roundtripped.chroma)
        d_tone = abs(original.tone - roundtripped.tone)
        worst_drift = max(worst_drift, d_hue, d_chroma, d_tone)
    if worst_drift > 1e-6:
        failures.append("HCT round-trip drift %.6f" % worst_drift)

    # CorePalette chroma assignment must match the reference.
    core = CorePalette(argb_from_hex("#6750A4"))
    if abs(core.a1.chroma - 48.0) > 1e-9:
        failures.append("CorePalette a1 chroma %r != 48" % core.a1.chroma)
    if abs(core.a2.chroma - 16.0) > 1e-9:
        failures.append("CorePalette a2 chroma %r != 16" % core.a2.chroma)
    if abs(core.a3.chroma - 24.0) > 1e-9:
        failures.append("CorePalette a3 chroma %r != 24" % core.a3.chroma)
    if abs(core.n1.chroma - 4.0) > 1e-9:
        failures.append("CorePalette n1 chroma %r != 4" % core.n1.chroma)
    if abs(core.n2.chroma - 8.0) > 1e-9:
        failures.append("CorePalette n2 chroma %r != 8" % core.n2.chroma)
    if abs(core.error.chroma - 84.0) > 1e-9:
        failures.append("CorePalette error chroma %r != 84" % core.error.chroma)
    if abs(core.a3.hue - 358.980997210704) > 1e-6:
        failures.append("CorePalette a3 hue %r != 358.98" % core.a3.hue)

    print("palette tones checked : %d" % (len(GOLDEN_PALETTES) * len(TONES)))
    print("clipping cases checked: %d" % len(GOLDEN_CLIPPING))
    print("hct round-trip drift  : %.2e" % worst_drift)
    print("invariants checked    : %d" % len(invariants))

    if failures:
        print()
        print("FAILURES (%d):" % len(failures))
        for f in failures[:25]:
            print("  " + f)
        if len(failures) > 25:
            print("  ... and %d more" % (len(failures) - 25))
        return 1

    print()
    print("RESULT: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())